#

In [ ]:
import pandas as pd
from pulp import *

# Basic Model

## Process the dataset

In [708]:
pd.set_option('display.max_columns', 500)
df = pd.read_excel("nutrition.xlsx",nrows=64)
df.head()

,INGREDIENT,dm,moist,ash,cp,cfat,cfibre,staew,sug,cho,ca,p,ip,k,na,cl,oebr,oelh,opp,lys,met,cys,mc,thr,trp,ile,arg,phe,his,leu,tyr,phetyr,val,dlysp,dmetp,dcysp,dmcp,dthrp,dtryp,dilep,dargp,dvalp,dneaa,c182,c20,ne2015mj,ne2015kcal,ewcvb2015,vppi,sidlys,sidmet,sidcys,sidmc,sidthr,sidtrp,sidile,sidneaa,decat,pcat,alyscat,ametcat,acyscat,amccat,athrcat,atrpcat,ailecat,aargcat,aphecat,ahiscat,aleucat,atyrcat,aptcat,avalcat
0,barley,867,133,19.941,99.705,27.0,43.350,539.274,22.542,0.0,0.4335,3.1212,2.3409,4.9419,0.0867,1.0404,2656.488,2861.967,1.2138,3.554700,1.734000,2.167500,3.901500,3.381300,1.21380,3.468000,4.855200,0.000000,0.000000,0.000000,0.000000,0.000000,4.855200,2.340900,1.300500,1.560600,2.861100,2.254200,0.867000,2.514300,3.901500,3.641400,41.009100,6.8493,0.0000,9.996510,2389.452000,1.135770,0.9537,2.68770,1.387200,1.734000,3.121200,2.687700,0.953700,2.861100,44.910600,0.0,0.00000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
1,blood,890,110,25.000,800.000,10.0,10.000,0.000,0.000,80.0,0.5000,1.7000,0.0000,2.7570,5.7897,3.4003,2450.000,2450.000,1.3000,71.201629,9.613035,9.613035,19.226069,35.193483,11.97556,9.613035,34.378819,55.226947,51.237842,102.475683,23.225458,78.452404,68.839104,51.250509,6.892057,6.892057,13.784114,25.368635,8.651731,6.892057,24.782077,49.564155,239.828921,0.0000,0.0000,7.185336,1716.415479,0.813849,1.0109,60.04888,7.625255,7.625255,15.250509,28.008147,9.824847,6.452138,263.584521,3690.0,1.00300,59.595764,7.527006,7.440489,14.9,27.556497,9.700204,6.229246,29.084481,45.727912,43.347214,85.772147,18.185533,63.9,56.998778
2,boneash,954,46,806.130,0.000,0.0,0.000,0.000,0.000,0.0,289.2528,133.7508,0.0000,0.3816,9.5400,0.0000,0.000,0.000,82.9000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.0000,0.000000,0.000000,0.000000,87.0000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,107.00064,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
3,copra,907,93,60.769,203.168,89.0,113.375,13.605,100.677,0.0,0.8163,5.5327,2.7210,21.2238,0.6349,6.1676,1889.000,1889.281,2.6303,5.079200,3.083800,3.083800,6.167600,6.076900,1.45120,6.530400,22.221500,0.000000,0.000000,0.000000,0.000000,0.000000,9.795600,2.358200,2.448900,1.632600,4.081500,3.628000,0.997700,4.897800,19.047000,7.528100,59.952700,1.2698,0.0000,9.051860,2163.195000,1.024910,1.2698,2.90240,1.814000,1.814000,3.628000,3.537300,0.816300,3.809400,49.522200,0.0,0.00000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
4,cotton,933,67,59.712,362.937,79.0,169.806,33.588,38.253,0.0,2.2392,10.1697,7.6506,14.3682,0.0000,0.2799,1730.000,1890.258,3.0789,14.928000,5.784600,6.157800,11.942400,11.662500,4.38510,11.289300,38.812800,0.000000,0.000000,0.000000,0.000000,0.000000,15.954300,8.770200,3.918600,4.198500,8.117100,8.023800,3.172200,8.117100,32.655000,11.849100,125.395200,28.3632,0.5598,6.829560,1633.683000,0.774390,2.8923,10.35630,4.665000,4.944900,9.609900,8.863500,3.545400,8.956800,139.763400,0.0,0.00000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000

In [709]:
df.columns = ['ingredient' if col.startswith('INGREDIENT') else col for col in df]

In [710]:
df.head()

,ingredient,dm,moist,ash,cp,cfat,cfibre,staew,sug,cho,ca,p,ip,k,na,cl,oebr,oelh,opp,lys,met,cys,mc,thr,trp,ile,arg,phe,his,leu,tyr,phetyr,val,dlysp,dmetp,dcysp,dmcp,dthrp,dtryp,dilep,dargp,dvalp,dneaa,c182,c20,ne2015mj,ne2015kcal,ewcvb2015,vppi,sidlys,sidmet,sidcys,sidmc,sidthr,sidtrp,sidile,sidneaa,decat,pcat,alyscat,ametcat,acyscat,amccat,athrcat,atrpcat,ailecat,aargcat,aphecat,ahiscat,aleucat,atyrcat,aptcat,avalcat
0,barley,867,133,19.941,99.705,27.0,43.350,539.274,22.542,0.0,0.4335,3.1212,2.3409,4.9419,0.0867,1.0404,2656.488,2861.967,1.2138,3.554700,1.734000,2.167500,3.901500,3.381300,1.21380,3.468000,4.855200,0.000000,0.000000,0.000000,0.000000,0.000000,4.855200,2.340900,1.300500,1.560600,2.861100,2.254200,0.867000,2.514300,3.901500,3.641400,41.009100,6.8493,0.0000,9.996510,2389.452000,1.135770,0.9537,2.68770,1.387200,1.734000,3.121200,2.687700,0.953700,2.861100,44.910600,0.0,0.00000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
1,blood,890,110,25.000,800.000,10.0,10.000,0.000,0.000,80.0,0.5000,1.7000,0.0000,2.7570,5.7897,3.4003,2450.000,2450.000,1.3000,71.201629,9.613035,9.613035,19.226069,35.193483,11.97556,9.613035,34.378819,55.226947,51.237842,102.475683,23.225458,78.452404,68.839104,51.250509,6.892057,6.892057,13.784114,25.368635,8.651731,6.892057,24.782077,49.564155,239.828921,0.0000,0.0000,7.185336,1716.415479,0.813849,1.0109,60.04888,7.625255,7.625255,15.250509,28.008147,9.824847,6.452138,263.584521,3690.0,1.00300,59.595764,7.527006,7.440489,14.9,27.556497,9.700204,6.229246,29.084481,45.727912,43.347214,85.772147,18.185533,63.9,56.998778
2,boneash,954,46,806.130,0.000,0.0,0.000,0.000,0.000,0.0,289.2528,133.7508,0.0000,0.3816,9.5400,0.0000,0.000,0.000,82.9000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0000,0.0000,0.000000,0.000000,0.000000,87.0000,0.00000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,107.00064,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
3,copra,907,93,60.769,203.168,89.0,113.375,13.605,100.677,0.0,0.8163,5.5327,2.7210,21.2238,0.6349,6.1676,1889.000,1889.281,2.6303,5.079200,3.083800,3.083800,6.167600,6.076900,1.45120,6.530400,22.221500,0.000000,0.000000,0.000000,0.000000,0.000000,9.795600,2.358200,2.448900,1.632600,4.081500,3.628000,0.997700,4.897800,19.047000,7.528100,59.952700,1.2698,0.0000,9.051860,2163.195000,1.024910,1.2698,2.90240,1.814000,1.814000,3.628000,3.537300,0.816300,3.809400,49.522200,0.0,0.00000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000
4,cotton,933,67,59.712,362.937,79.0,169.806,33.588,38.253,0.0,2.2392,10.1697,7.6506,14.3682,0.0000,0.2799,1730.000,1890.258,3.0789,14.928000,5.784600,6.157800,11.942400,11.662500,4.38510,11.289300,38.812800,0.000000,0.000000,0.000000,0.000000,0.000000,15.954300,8.770200,3.918600,4.198500,8.117100,8.023800,3.172200,8.117100,32.655000,11.849100,125.395200,28.3632,0.5598,6.829560,1633.683000,0.774390,2.8923,10.35630,4.665000,4.944900,9.609900,8.863500,3.545400,8.956800,139.763400,0.0,0.00000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.000000

In [711]:
print(df.columns.tolist())

['ingredient', 'dm', 'moist', 'ash', 'cp', 'cfat', 'cfibre', 'staew', 'sug', 'cho', 'ca', 'p', 'ip', 'k', 'na', 'cl', 'oebr', 'oelh', 'opp', 'lys', 'met', 'cys', 'mc', 'thr', 'trp', 'ile', 'arg', 'phe', 'his', 'leu', 'tyr', 'phetyr', 'val', 'dlysp', 'dmetp', 'dcysp', 'dmcp', 'dthrp', 'dtryp', 'dilep', 'dargp', 'dvalp', 'dneaa', 'c182', 'c20', 'ne2015mj', 'ne2015kcal', 'ewcvb2015', 'vppi', 'sidlys', 'sidmet', 'sidcys', 'sidmc', 'sidthr', 'sidtrp', 'sidile', 'sidneaa', 'decat', 'pcat', 'alyscat', 'ametcat', 'acyscat', 'amccat', 'athrcat', 'atrpcat', 'ailecat', 'aargcat', 'aphecat', 'ahiscat', 'aleucat', 'atyrcat', 'aptcat', 'avalcat']

In [712]:
food_items = list(df['ingredient'])

In [713]:
print("So, the food items to consdier, are\n"+"-"*100)
for f in food_items:
    print(f,end=', ')

So, the food items to consdier, are
----------------------------------------------------------------------------------------------------
barley, blood, boneash, copra, cotton, fats, fish, fishlq, gnseeds, gncake, maize, maizebranhighq, maizebranlowq, mbmeal, sugars, pkcake, palmoil, rapecake, rapemeal, rice, sesamecake, sorghum, soybeanexp, soybeanhulls, soybeanmeal, soybeanheat, sunflower, sunflowerseeds, tapbran, caswhole, casfine, cascoarse, wheat, wheatbran, dicaph, monocapo, lime, shells, salt,

In [714]:
import numpy as np
df.shape

(39, 73)

In [715]:
np.random.seed(0)
# df['Price/kg'] = random.rand(39,1)*10
df['Price/kg'] = np.ones(39)*10

## Create dictionary of nutrition for all food items

In [716]:
#From here, write the interface of what nutrition dataframe to choose.
#And the format of the data frame should include [Name]
#nutrition_df=???

In [717]:
nutrition_df=pd.read_excel('quantity.xlsx')

In [718]:
nutrition_df

   Afkorting in WEBCALCULATOR  unit  Minimum  Maximum          Rule in webapp
0                        oebr  kcal   2650.0   2700.0  oebr btw 2650 and 2700
1                        oelh  kcal      0.0      NaN               oelh gt 0
2                          cp  g/kg    152.0    200.0      cp btw 152 and 200
3                        cfat  g/kg      0.0      NaN               cfat gt 0
4                      cfibre  g/kg      0.0     65.0     cfibre btw 0 and 65
5                       staew  g/kg    310.0      NaN            staew gt 310
6                          ca  g/kg      7.9      8.9      ca btw 7.9 and 8.9
7                          na  g/kg      1.4      1.7      na btw 1.4 and 1.7
8                         opp  g/kg      3.8      NaN              opp gt 3.8
9                       dlysp  g/kg      8.2      9.1   dlysp btw 8.2 and 9.1
10                      dmetp  g/kg      3.4      NaN            dmetp gt 3.4
11                       dmcp  g/kg      6.3      7.3    dmcp btw 6.3 and 7.3
12                      dthrp  g/kg      5.5      NaN            dthrp gt 5.5
13                      dtryp  g/kg      1.5      NaN            dtryp gt 1.5
14                      dvalp  g/kg      6.7      NaN            dvalp gt 6.7
15                      dargp  g/kg      8.6      NaN            dargp gt 8.6

In [719]:
#Extract all the nutritions included
nutrition=[]
for i in range (len(nutrition_df)):
    nutrition.append(nutrition_df.iloc[i][0])

In [720]:
#Create dictionay for every single nutrition. The dictionary includes the amount contained in different ingredient.
for i in range(len(nutrition)):
    vars()[nutrition[i]] = dict(zip(food_items,df[nutrition[i]]))

In [721]:
food_vars = LpVariable.dicts("Portion",food_items,lowBound=0,cat='Continuous')

## Dealing with costs

In [722]:
print(food_items)

['barley', 'blood', 'boneash', 'copra', 'cotton', 'fats', 'fish', 'fishlq', 'gnseeds', 'gncake', 'maize', 'maizebranhighq', 'maizebranlowq', 'mbmeal', 'sugars', 'pkcake', 'palmoil', 'rapecake', 'rapemeal', 'rice', 'sesamecake', 'sorghum', 'soybeanexp', 'soybeanhulls', 'soybeanmeal', 'soybeanheat', 'sunflower', 'sunflowerseeds', 'tapbran', 'caswhole', 'casfine', 'cascoarse', 'wheat', 'wheatbran', 'dicaph', 'monocapo', 'lime', 'shells', 'salt']

In [723]:
cost_df_raw=pd.read_excel('costs.xlsx')

In [724]:
food_items_df=pd.DataFrame(food_items,columns=['food'])

In [725]:
costs_df=food_items_df.merge(cost_df,left_on='food',right_on='Ingredients')

In [726]:
costs_df=costs_df.drop('food',axis=1)

In [727]:
costs_df.head()

  Ingredients  Price
0      barley    105
1       blood    285
2     boneash     70
3       copra     65
4      cotton     80

In [728]:
costs={}
for i in range (len(costs_df)):
    costs[costs_df['Ingredients'].iloc[i]]=costs_df['Price'].iloc[i]

In [729]:
print(costs)
len(costs)

{'barley': 105, 'blood': 285, 'boneash': 70, 'copra': 65, 'cotton': 80, 'fats': 600, 'fish': 250, 'fishlq': 220, 'gnseeds': 235, 'gncake': 200, 'maize': 130, 'maizebranhighq': 75, 'maizebranlowq': 60, 'mbmeal': 135, 'sugars': 85, 'pkcake': 50, 'palmoil': 600, 'rapecake': 125, 'rapemeal': 87, 'rice': 45, 'sesamecake': 97, 'sorghum': 150, 'soybeanexp': 150, 'soybeanhulls': 30, 'soybeanmeal': 150, 'soybeanheat': 250, 'sunflower': 81, 'sunflowerseeds': 195, 'tapbran': 90, 'caswhole': 60, 'casfine': 70, 'cascoarse': 65, 'wheat': 110, 'wheatbran': 70, 'dicaph': 350, 'monocapo': 375, 'lime': 20, 'shells': 45, 'salt': 100}

39

In [730]:
#If setting the costs as unified one.
#costs =dict(zip(food_items,df['Price/kg']))

## Add the objective function

In [731]:
prob = LpProblem("Smallholder Layer Starter Diet",LpMinimize)

In [732]:
# The objective function is added to 'prob' first
prob += lpSum([costs[i]*food_vars[i] for i in food_items]), "Total Cost of the balanced diet"

## Adding constraints

In [733]:
print(nutrition)

['oebr', 'oelh', 'cp', 'cfat', 'cfibre', 'staew', 'ca', 'na', 'opp', 'dlysp', 'dmetp', 'dmcp', 'dthrp', 'dtryp', 'dvalp', 'dargp']

In [734]:
###############TEST
# nutrition_df.drop(nutrition_df.index[3],inplace=True)
# nutrition_df=nutrition_df.reset_index(drop=True)

In [735]:
for i in range(len(nutrition_df)):
    n = vars()[nutrition_df.iloc[i,0]]
#     print(n)
    print('Min',i)
    
    prob += lpSum([n[f]* food_vars[f] for f in food_items]) >= nutrition_df['Minimum'][i]
    if (i in nutrition_df[nutrition_df['Maximum']>0].index):
        print('Max',i)
        prob += lpSum([n[f]* food_vars[f] for f in food_items]) <= nutrition_df['Maximum'][i]
    print('------')

Min 0
Max 0
------
Min 1
------
Min 2
Max 2
------
Min 3
------
Min 4
Max 4
------
Min 5
------
Min 6
Max 6
------
Min 7
Max 7
------
Min 8
------
Min 9
Max 9
------
Min 10
------
Min 11
Max 11
------
Min 12
------
Min 13
------
Min 14
------
Min 15
------

In [736]:
print(costs)
len(costs)

{'barley': 105, 'blood': 285, 'boneash': 70, 'copra': 65, 'cotton': 80, 'fats': 600, 'fish': 250, 'fishlq': 220, 'gnseeds': 235, 'gncake': 200, 'maize': 130, 'maizebranhighq': 75, 'maizebranlowq': 60, 'mbmeal': 135, 'sugars': 85, 'pkcake': 50, 'palmoil': 600, 'rapecake': 125, 'rapemeal': 87, 'rice': 45, 'sesamecake': 97, 'sorghum': 150, 'soybeanexp': 150, 'soybeanhulls': 30, 'soybeanmeal': 150, 'soybeanheat': 250, 'sunflower': 81, 'sunflowerseeds': 195, 'tapbran': 90, 'caswhole': 60, 'casfine': 70, 'cascoarse': 65, 'wheat': 110, 'wheatbran': 70, 'dicaph': 350, 'monocapo': 375, 'lime': 20, 'shells': 45, 'salt': 100}

39

In [737]:
'''
prob += lpSum([oebr[f] * food_vars[f] for f in food_items]) >= 2650.0, "oebrMin"
prob += lpSum([oebr[f] * food_vars[f] for f in food_items]) <= 2700.0, "oebrMax"

prob += lpSum([oelh[f] * food_vars[f] for f in food_items]) >= 0, "oelhMin"

prob += lpSum([cp[f] * food_vars[f] for f in food_items]) >= 152.0, "cpMin"
prob += lpSum([cp[f] * food_vars[f] for f in food_items]) <= 200.0, "cpMax"

prob += lpSum([cfibre[f] * food_vars[f] for f in food_items]) >= 0, "cfibreMin"
prob += lpSum([cfibre[f] * food_vars[f] for f in food_items]) <= 65.0, "cfibreMax"

prob += lpSum([staew[f] * food_vars[f] for f in food_items]) >= 310.0, "staewMin"

prob += lpSum([ca[f] * food_vars[f] for f in food_items]) >= 7.9, "caMin"
prob += lpSum([ca[f] * food_vars[f] for f in food_items]) <= 8.9, "caMax"

prob += lpSum([na[f] * food_vars[f] for f in food_items]) >=1.4, "naMin"
prob += lpSum([na[f] * food_vars[f] for f in food_items]) <= 1.7, "naMax"

prob += lpSum([opp[f] * food_vars[f] for f in food_items]) >=3.8, "oppMin"

prob += lpSum([dlysp[f] * food_vars[f] for f in food_items]) >=8.2, "dlyspMin"
prob += lpSum([dlysp[f] * food_vars[f] for f in food_items]) <= 9.1, "dlyspMax"

prob += lpSum([dmetp[f] * food_vars[f] for f in food_items]) >=3.4, "dmetpMin"

prob += lpSum([dmcp[f] * food_vars[f] for f in food_items]) >=6.3, "dmcpMin"
prob += lpSum([dmcp[f] * food_vars[f] for f in food_items]) <= 7.3, "dmcpMax"

prob += lpSum([dthrp[f] * food_vars[f] for f in food_items]) >=5.5, "dthrpMin"

prob += lpSum([dtryp[f] * food_vars[f] for f in food_items]) >=1.5, "dtrypMin"

prob += lpSum([dvalp[f] * food_vars[f] for f in food_items]) >=6.7, "dvalpMin"

prob += lpSum([dargp[f] * food_vars[f] for f in food_items]) >=8.6, "dargpMin"
'''

'\nprob += lpSum([oebr[f] * food_vars[f] for f in food_items]) >= 2650.0, "oebrMin"\nprob += lpSum([oebr[f] * food_vars[f] for f in food_items]) <= 2700.0, "oebrMax"\n\nprob += lpSum([oelh[f] * food_vars[f] for f in food_items]) >= 0, "oelhMin"\n\nprob += lpSum([cp[f] * food_vars[f] for f in food_items]) >= 152.0, "cpMin"\nprob += lpSum([cp[f] * food_vars[f] for f in food_items]) <= 200.0, "cpMax"\n\nprob += lpSum([cfibre[f] * food_vars[f] for f in food_items]) >= 0, "cfibreMin"\nprob += lpSum([cfibre[f] * food_vars[f] for f in food_items]) <= 65.0, "cfibreMax"\n\nprob += lpSum([staew[f] * food_vars[f] for f in food_items]) >= 310.0, "staewMin"\n\nprob += lpSum([ca[f] * food_vars[f] for f in food_items]) >= 7.9, "caMin"\nprob += lpSum([ca[f] * food_vars[f] for f in food_items]) <= 8.9, "caMax"\n\nprob += lpSum([na[f] * food_vars[f] for f in food_items]) >=1.4, "naMin"\nprob += lpSum([na[f] * food_vars[f] for f in food_items]) <= 1.7, "naMax"\n\nprob += lpSum([opp[f] * food_vars[f] for f in food_items]) >=3.8, "oppMin"\n\nprob += lpSum([dlysp[f] * food_vars[f] for f in food_items]) >=8.2, "dlyspMin"\nprob += lpSum([dlysp[f] * food_vars[f] for f in food_items]) <= 9.1, "dlyspMax"\n\nprob += lpSum([dmetp[f] * food_vars[f] for f in food_items]) >=3.4, "dmetpMin"\n\nprob += lpSum([dmcp[f] * food_vars[f] for f in food_items]) >=6.3, "dmcpMin"\nprob += lpSum([dmcp[f] * food_vars[f] for f in food_items]) <= 7.3, "dmcpMax"\n\nprob += lpSum([dthrp[f] * food_vars[f] for f in food_items]) >=5.5, "dthrpMin"\n\nprob += lpSum([dtryp[f] * food_vars[f] for f in food_items]) >=1.5, "dtrypMin"\n\nprob += lpSum([dvalp[f] * food_vars[f] for f in food_items]) >=6.7, "dvalpMin"\n\nprob += lpSum([dargp[f] * food_vars[f] for f in food_items]) >=8.6, "dargpMin"\n'

In [738]:
# The problem data is written to an .lp file
prob.writeLP("SimpleDietProblem.lp")
# The problem is solved using PuLP's choice of Solver
prob.solve(pulp.PULP_CBC_CMD())

1

In [739]:
print("Solution"+"-"*100)
for v in prob.variables():
    if v.varValue>0 and v.name[0]=='P':
        print(v.name, "=", v.varValue,'kg')

Solution----------------------------------------------------------------------------------------------------
Portion_boneash = 0.0018651074 kg
Portion_caswhole = 0.073674343 kg
Portion_fish = 0.070430241 kg
Portion_maizebranhighq = 0.13354586 kg
Portion_monocapo = 0.00083770807 kg
Portion_rapemeal = 0.20423689 kg
Portion_rice = 0.48865891 kg
Portion_salt = 0.0012428947 kg
Portion_wheat = 0.067520956 kg

In [740]:
print("The total cost of this balanced diet is: {} in Nigeria Currency ".format(round(value(prob.objective),2)))

The total cost of this balanced diet is: 79.8 in Nigeria Currency

# Extension 1-1

In [741]:
prob2 = LpProblem("Smallholder Layer Starter Diet",LpMinimize)

In [742]:
food_chosen = LpVariable.dicts("Chosen",food_items,0,1,cat='Integer')

In [743]:
# The objective function is added to 'prob' first
prob2 += lpSum([costs[i]*food_vars[i] for i in food_items]), "Total Cost of the balanced diet"

In [744]:
for i in range(len(nutrition_df)):
    n = vars()[nutrition_df.iloc[i,0]]
#     print(n)
    print('Min',i)
    
    prob2 += lpSum([n[f]* food_vars[f] for f in food_items]) >= nutrition_df['Minimum'][i]
    if (i in nutrition_df[nutrition_df['Maximum']>0].index):
        print('Max',i)
        prob2 += lpSum([n[f]* food_vars[f] for f in food_items]) <= nutrition_df['Maximum'][i]
    print('------')

Min 0
Max 0
------
Min 1
------
Min 2
Max 2
------
Min 3
------
Min 4
Max 4
------
Min 5
------
Min 6
Max 6
------
Min 7
Max 7
------
Min 8
------
Min 9
Max 9
------
Min 10
------
Min 11
Max 11
------
Min 12
------
Min 13
------
Min 14
------
Min 15
------

In [745]:

for f in food_items:
#     prob2 += food_vars[f]>= food_chosen[f]*0.1
    prob2 += food_vars[f]>= 0

    prob2 += food_vars[f]<= food_chosen[f]*1e5

In [746]:
#Interface for selecting the Number of ingredients
MaxNum=3

In [747]:
prob2+= lpSum([food_chosen[f] for f in food_items])<=MaxNum
# The problem is solved using PuLP's choice of Solver
prob2.solve(pulp.PULP_CBC_CMD())
print("Solution"+"-"*100)
for v in prob2.variables():
    if v.varValue>0 and v.name[0]=='P':
        print(v.name, "=", v.varValue,'kg')
print("The total cost of this balanced diet is: {} in Nigeria Currency ".format(round(value(prob2.objective),2)))

Solution----------------------------------------------------------------------------------------------------
Portion_fish = 0.13110074 kg
Portion_wheat = 0.53863388 kg
Portion_wheatbran = 0.42978379 kg
The total cost of this balanced diet is: 122.11 in Nigeria Currency

# Extension 1-0

In [ ]:
prob3 = LpProblem("Smallholder Layer Starter Diet",LpMinimize)

In [ ]:
prob3 += lpSum([costs[i]*food_vars[i] for i in food_items]), "Total Cost of the balanced diet"

In [ ]:
for i in range(len(nutrition_df)):
    n = vars()[nutrition_df.iloc[i,0]]
#     print(n)
    print('Min',i)
    
    prob3 += lpSum([n[f]* food_vars[f] for f in food_items]) >= nutrition_df['Minimum'][i]
    if (i in nutrition_df[nutrition_df['Maximum']>0].index):
        print('Max',i)
        prob3 += lpSum([n[f]* food_vars[f] for f in food_items]) <= nutrition_df['Maximum'][i]
    print('------')